// <auto-generated />
using System;
using EF_Champions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFChampions.Migrations
{
    [DbContext(typeof(StubbedContext))]
    partial class StubbedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("EF_Champions.Entities.ChampionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = 1,
                            Name = "Akali"
                        },
                        new
                        {
                            Id = 2,
                            Class = 2,
                            Name = "Aatrox"
                        });
                });

            modelBuilder.Entity("EF_Champions.Entities.SkinEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampionForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ChampionForeignKey");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChampionForeignKey = 1,
                            Name = "Skin1"
                        },
                        new
                        {
                            Id = 2,
                            ChampionForeignKey = 1,
                            Name = "Skin2"
                        },
                        new
                        {
                            Id = 3,
                            ChampionForeignKey = 2,
                            Name = "Skin3"
                        },
                        new
                        {
                            Id = 4,
                            ChampionForeignKey = 2,
                            Name = "Skin4"
                        });
                });

            modelBuilder.Entity("EF_Champions.Entities.SkinEntity", b =>
                {
                    b.HasOne("EF_Champions.Entities.ChampionEntity", "Champion")
                        .WithMany("Skins")
                        .HasForeignKey("ChampionForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("EF_Champions.Entities.ChampionEntity", b =>
                {
                    b.Navigation("Skins");
                });
#pragma warning restore 612, 618
        }
    }
}
